apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Values.App }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.App }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    ports:
      - protocol: TCP
        port: 9332
      - protocol: TCP
        port: 9333
