apiVersion: v1
kind: Service
metadata:
  name: "echo-env-service"
  labels:
    app: {{ .Values.app }}
    release: {{ .Release.Name }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.service.dnsname }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.app }}
    release: {{ .Release.Name }}
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
